services:
  nodejs: 
    image: node
    ports:
      - 4000:4000
    env_file:
      ./.env
    container_name: nodejs
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
  web:
    image: nginx:alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    container_name: web
    depends_on:
      - nodejs
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ahli
    container_name: postgres  

    volumes:
      - postgres-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 1010:8080

volumes:
 postgres-db:
